search_tweets_api:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/dev.json
  consumer_key: fKqrUWh5n5ndQRXZRJSO8uitf
  consumer_secret: jBhllJ7UocplVQagryjd0kx7myrV7SzOmWK7OyXFSgtfGkLDqv